export const OPEN_MODAL  = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const MODAL_ORDER_CONSULT = 'MODAL_ORDER_CONSULT'
export const MODAL_GET_OFFER = 'MODAL_GET_OFFER'
export const MODAL_GET_INFO = 'MODAL_GET_INFO'
export const MODAL_GET_REPORTS = 'MODAL_GET_REPORTS'
